NumPy is a Linear Algebra Library for Python. It's quite important for Data Science because almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks. NumPy is useful for its arrays. These come in two flavors: vectors and matrices. To install NumPy...

pip3 install numpy

Here are a few different ways that you can create NumPy arrays...

In [3]:
import numpy as np
my_list = [1, 2, 3]
arr = np.array(my_list)
print(arr)

[1 2 3]


In [6]:
my_matrix = [[1, 2, 3], [4, 5, 6]]
print(np.array(my_matrix))

[[1 2 3]
 [4 5 6]]


The syntax for arange is (start, stop, step size)

In [7]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])